# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-13 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(help_text='博客内容')),
                ('pub', models.DateTimeField(verbose_name='发布时间')),
            ],
            options={
                'ordering': ['-pub'],
                'verbose_name_plural': '博客',
                'verbose_name': '博客',
            },
        ),
    ]
